-- MySQL Script generated by MySQL Workbench
-- 10/09/15 17:47:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema universities
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universities
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universities` DEFAULT CHARACTER SET utf8 ;
USE `universities` ;

-- -----------------------------------------------------
-- Table `universities`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`courses` (
  `course_id` INT(11) NOT NULL COMMENT '',
  `department_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`course_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`faculties` (
  `faculty_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`faculty_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`departments` (
  `department_id` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(200) NOT NULL COMMENT '',
  `faculty_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`department_id`)  COMMENT '',
  INDEX `FK_Departments_Faculties` (`faculty_id` ASC)  COMMENT '',
  CONSTRAINT `FK_Departments_Faculties`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `universities`.`faculties` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`professors` (
  `professor_id` INT(11) NOT NULL COMMENT '',
  `first_name` VARCHAR(100) NOT NULL COMMENT '',
  `last_name` VARCHAR(100) NOT NULL COMMENT '',
  `department_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`professor_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`departments_professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`departments_professors` (
  `department_id` INT(11) NOT NULL COMMENT '',
  `professor_id` INT(11) NOT NULL COMMENT '',
  INDEX `FK_Departments_Professors_Departments` (`department_id` ASC)  COMMENT '',
  INDEX `FK_Departments_Professors_Professors` (`professor_id` ASC)  COMMENT '',
  PRIMARY KEY (`department_id`, `professor_id`)  COMMENT '',
  CONSTRAINT `FK_Departments_Professors_Departments`
    FOREIGN KEY (`department_id`)
    REFERENCES `universities`.`departments` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Departments_Professors_Professors`
    FOREIGN KEY (`professor_id`)
    REFERENCES `universities`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`professors_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`professors_courses` (
  `professor_id` INT(11) NOT NULL COMMENT '',
  `course_id` INT(11) NOT NULL COMMENT '',
  INDEX `FK_Professors_Courses_Courses` (`course_id` ASC)  COMMENT '',
  INDEX `FK_Professors_Courses_Professors` (`professor_id` ASC)  COMMENT '',
  PRIMARY KEY (`professor_id`, `course_id`)  COMMENT '',
  CONSTRAINT `FK_Professors_Courses_Courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `universities`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Professors_Courses_Professors`
    FOREIGN KEY (`professor_id`)
    REFERENCES `universities`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`titles` (
  `title_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(200) NOT NULL COMMENT '',
  PRIMARY KEY (`title_id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`professors_titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`professors_titles` (
  `professor_id` INT(11) NOT NULL COMMENT '',
  `title_id` DATETIME NOT NULL COMMENT '',
  INDEX `FK_Professors_Titles_Professors` (`professor_id` ASC)  COMMENT '',
  INDEX `FK_Professors_Titles_Titles` (`title_id` ASC)  COMMENT '',
  PRIMARY KEY (`title_id`, `professor_id`)  COMMENT '',
  CONSTRAINT `FK_Professors_Titles_Professors`
    FOREIGN KEY (`professor_id`)
    REFERENCES `universities`.`professors` (`professor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Professors_Titles_Titles`
    FOREIGN KEY (`title_id`)
    REFERENCES `universities`.`titles` (`title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`students` (
  `student_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `faculty_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`student_id`)  COMMENT '',
  INDEX `FK_Students_Faculties` (`faculty_id` ASC)  COMMENT '',
  CONSTRAINT `FK_Students_Faculties`
    FOREIGN KEY (`faculty_id`)
    REFERENCES `universities`.`faculties` (`faculty_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`students_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`students_courses` (
  `student_id` INT(11) NOT NULL COMMENT '',
  `course_id` INT(11) NOT NULL COMMENT '',
  INDEX `FK_Students_Courses_Courses` (`course_id` ASC)  COMMENT '',
  INDEX `FK_Students_Courses_Students` (`student_id` ASC)  COMMENT '',
  PRIMARY KEY (`student_id`, `course_id`)  COMMENT '',
  CONSTRAINT `FK_Students_Courses_Courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `universities`.`courses` (`course_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Students_Courses_Students`
    FOREIGN KEY (`student_id`)
    REFERENCES `universities`.`students` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `universities`.`sysdiagrams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universities`.`sysdiagrams` (
  `name` VARCHAR(160) NOT NULL COMMENT '',
  `principal_id` INT(11) NOT NULL COMMENT '',
  `diagram_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `version` INT(11) NULL DEFAULT NULL COMMENT '',
  `definition` LONGBLOB NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`diagram_id`)  COMMENT '',
  UNIQUE INDEX `UK_principal_name` (`principal_id` ASC, `name` ASC)  COMMENT '')
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
